name: signal
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_icons: ^1.1.0
  convert: ^2.1.1
  keyboard_avoider: ^0.1.2
  redux_thunk: ^0.4.0
  http: ^0.12.0+1
  redux: ^5.0.0
  flutter_redux: ^0.8.2
  axios: ^1.0.1+1
  fluttertoast: ^3.1.0 
  localstorage: ^4.0.0+1
  shared_preferences: ^2.0.5
  socket_io_client: ^1.0.1
  intl: ^0.16.1
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - images/
